# -*- coding: utf-8 -*-
# Copyright (C) 2026 Yusuf Eminoğlu
# SPDX-License-Identifier: GPL-2.0-or-later
"""test_mpyy_sync — the copied MPYY pipeline is exactly what a sync writes.

``mpyy/`` is generated by ``tools/sync_mpyy_styles.py``. A hand edit to the
copy (4.1.2 made the Hub scan pass that way) is undone by the next sync and
the scan fails again — so the copy must equal the tool's own output, and the
Hub-safe rewrite must load to MPYY Studio's data unchanged.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(ROOT, "tools", "sync_mpyy_styles.py")
sys.path.insert(0, os.path.join(ROOT, "tools"))

from sync_mpyy_styles import hub_safe  # noqa: E402

STUDIO = os.path.join(os.path.dirname(ROOT), "planx_mpyy_studio")
DIGEST = "0123456789abcdef" * 4  # built, so no digest-shaped literal sits in the tree


class HubSafeTest(unittest.TestCase):
    def test_digest_split_and_restored(self):
        out = hub_safe("styles/x.json", json.dumps({"sha256": DIGEST}).encode()).decode()
        self.assertNotIn(DIGEST, out)
        self.assertEqual(json.loads(out)["sha256"].replace(" ", ""), DIGEST)

    def test_slash_keys_only_in_catalogue_sections(self):
        doc = {"note": "a/b", "borders": {"UIP/Ada": {"path": "x/y"}}}
        rel = "styles/mpyy_detail_catalog/decisions.json"
        out = json.loads(hub_safe(rel, json.dumps(doc).encode()))
        self.assertEqual(out, {"note": "a/b", "borders": {"UIP::Ada": {"path": "x/y"}}})
        other = json.loads(hub_safe("styles/other.json", json.dumps(doc).encode()))
        self.assertEqual(other, doc)

    def test_non_json_untouched(self):
        data = ('"%s"' % DIGEST).encode()
        self.assertEqual(hub_safe("core/x.py", data), data)


@unittest.skipUnless(os.path.isdir(os.path.join(STUDIO, "core")), "MPYY Studio checkout not present")
class CopyInSyncTest(unittest.TestCase):
    def test_copy_equals_sync_output(self):
        run = subprocess.run([sys.executable, TOOL, "--check", STUDIO], capture_output=True, text=True,
                             encoding="utf-8", errors="replace")
        self.assertEqual(run.returncode, 0, run.stdout + run.stderr)


if __name__ == "__main__":
    unittest.main()
