<?xml version='1.0' encoding='utf-8'?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
  <NamedLayer><Name>CDP_TURIZM_ALANI</Name><UserStyle><Title>CDP_TURIZM_ALANI</Title><FeatureTypeStyle>
    <Rule><Name>0</Name><Title>TURIZM_BOLGESI</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>TurizmBolgesi</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:0ac90c42-7dca-40b9-8899-26468338c34b.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:TurizmAlani.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>GUNUBIRLIK_TURIZM</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>GunubirlikTurizm</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:a8dda4b0-34c9-416c-9dd8-c175c1c127c4.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:GunubirlikTurizm.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>YAYLA_TURIZMI</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>YaylaTurizmi</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:8939c6f0-8534-4abe-a1f4-4b87926eb352.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:YaylaTurizmi.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>KIS_TURIZMI</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>KisTurizmi</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:0059bd4f-a7e1-48ae-97b6-8ae40fd67ba5.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:KisTurizmi.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>GOLF_TURIZMI</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>GolfTurizmi</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:47360f2c-a6fd-44fd-a960-eb05f2363453.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:GolfTurizmi.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>EKOTURIZM</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>EkoTurizm</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:dd9b592b-c1cd-43c1-8464-68440161ff9f.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:Ekoturizm.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
    <Rule><Name>0</Name><Title>SAGLIK_TURIZMI</Title><MaxScaleDenominator>500000</MaxScaleDenominator><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>TurizmTip</ogc:PropertyName><ogc:Literal>SaglikTurizmi</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><GraphicFill><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-tarama:fe8f13b3-9b38-4267-861b-73a1b8b20725.png" /><Format>image/png</Format></ExternalGraphic></Graphic></GraphicFill></Fill></PolygonSymbolizer><PointSymbolizer><Graphic><ExternalGraphic><OnlineResource xlink:type="simple" xlink:href="mpyy-eksik-sembol:SaglikTurizmi.svg" /><Format>image/svg</Format></ExternalGraphic><Size>34</Size></Graphic></PointSymbolizer></Rule>
  </FeatureTypeStyle></UserStyle></NamedLayer>
</StyledLayerDescriptor>