# -*- coding: utf-8 -*-
"""Official MPYY UİP tabaka catalog (generated file).

Compiled by ``tools/compile_mpyy_catalog.py`` from the Mekânsal Planlar
Yapım Yönetmeliği UİP database published by the T.C. Çevre, Şehircilik ve
İklim Değişikliği Bakanlığı. Do not edit by hand; re-run the compiler.

Gives each UİP tabaka its official identity — upper group and code, function
and code — so the PlanGML schema columns of an imported plan carry the
Ministry's own values. ``MPYY_ALIASES`` maps local spellings seen in real
municipal drawings onto the official tabaka they are the same function as.

The codes and names below are the official standard and are not claimed as
original work; see THIRD_PARTY_NOTICES.md. The compiler, the alias list and
this catalog's structure are:

Copyright (C) 2026 Yusuf Eminoğlu
SPDX-License-Identifier: GPL-2.0-or-later
"""

MPYY_TABAKA = {'ADAKENARI': {'fonksiyon_adi': 'ADAKENARI',
               'fonksiyon_kodu': '130100',
               'geometri': 'LINE',
               'ust_grup_adi': 'ÖZEL ÇİZGİLER',
               'ust_grup_id': '130000'},
 'HAT_AKARYAKIT_BORU': {'fonksiyon_adi': 'AKARYAKIT BORU HATTI',
                        'fonksiyon_kodu': '106101',
                        'geometri': 'LINE',
                        'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                        'ust_grup_id': '106000'},
 'HAT_ANA_ICME_SUYU': {'fonksiyon_adi': 'İÇME SUYU ANA HATTI',
                       'fonksiyon_kodu': '117101',
                       'geometri': 'LINE',
                       'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                       'ust_grup_id': '117000'},
 'HAT_ATIKSU_DESARJ': {'fonksiyon_adi': 'ATIK SU DERİN DENİZ DEŞARJ HATTI',
                       'fonksiyon_kodu': '117102',
                       'geometri': 'LINE',
                       'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                       'ust_grup_id': '117000'},
 'HAT_ATIKSU_KOLLEKTOR': {'fonksiyon_adi': 'ATIK SU ANA KOLLEKTÖRÜ',
                          'fonksiyon_kodu': '117103',
                          'geometri': 'LINE',
                          'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                          'ust_grup_id': '117000'},
 'HAT_BORU_HATTI': {'fonksiyon_adi': 'BORU HATTI',
                    'fonksiyon_kodu': '106102',
                    'geometri': 'LINE',
                    'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                    'ust_grup_id': '106000'},
 'HAT_CEBRI_BORU': {'fonksiyon_adi': 'CEBRİ BORU HATTI',
                    'fonksiyon_kodu': '106103',
                    'geometri': 'LINE',
                    'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                    'ust_grup_id': '106000'},
 'HAT_DEMIRYOLU': {'fonksiyon_adi': 'DEMİRYOLU',
                   'fonksiyon_kodu': '104100',
                   'geometri': 'LINE',
                   'ust_grup_adi': 'DEMİRYOLLARI',
                   'ust_grup_id': '104000'},
 'HAT_DOGALGAZ': {'fonksiyon_adi': 'DOĞALGAZ BORU HATTI',
                  'fonksiyon_kodu': '106104',
                  'geometri': 'LINE',
                  'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                  'ust_grup_id': '106000'},
 'HAT_ENERJI_NAKIL_HAT': {'fonksiyon_adi': 'ENERJİ NAKİL HATTI',
                          'fonksiyon_kodu': '106105',
                          'geometri': 'LINE',
                          'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                          'ust_grup_id': '106000'},
 'HAT_HAVAI': {'fonksiyon_adi': 'HAVAİ HAT',
               'fonksiyon_kodu': '111101',
               'geometri': 'LINE',
               'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
               'ust_grup_id': '111000'},
 'HAT_HAVARAY': {'fonksiyon_adi': 'HAVARAY',
                 'fonksiyon_kodu': '111102',
                 'geometri': 'LINE',
                 'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
                 'ust_grup_id': '111000'},
 'HAT_HIZLI_TREN': {'fonksiyon_adi': 'HIZLI TREN HATTI',
                    'fonksiyon_kodu': '104101',
                    'geometri': 'LINE',
                    'ust_grup_adi': 'DEMİRYOLLARI',
                    'ust_grup_id': '104000'},
 'HAT_IFRAZ': {'fonksiyon_adi': 'İFRAZ HATTI',
               'fonksiyon_kodu': '132102',
               'geometri': 'LINE',
               'ust_grup_adi': 'YAPI DÜZENİ VE YOĞUNLUKLARI',
               'ust_grup_id': '132000'},
 'HAT_ILETIM_TUNELI': {'fonksiyon_adi': 'İLETİM TÜNELİ',
                       'fonksiyon_kodu': '106106',
                       'geometri': 'LINE',
                       'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                       'ust_grup_id': '106000'},
 'HAT_KADEME': {'fonksiyon_adi': 'KADEME HATTI',
                'fonksiyon_kodu': '132101',
                'geometri': 'LINE',
                'ust_grup_adi': 'YAPI DÜZENİ VE YOĞUNLUKLARI',
                'ust_grup_id': '132000'},
 'HAT_OTOYOL': {'fonksiyon_adi': 'ERİŞME KONTROLLÜ KARAYOLU (OTOYOL)',
                'fonksiyon_kodu': '133001',
                'geometri': 'LINE',
                'ust_grup_adi': 'KARAYOLLARI',
                'ust_grup_id': '133000'},
 'HAT_RAYLI_TOPLU_TAS': {'fonksiyon_adi': 'RAYLI TOPLU TAŞIMA HATTI',
                         'fonksiyon_kodu': '111103',
                         'geometri': 'LINE',
                         'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
                         'ust_grup_id': '111000'},
 'HAT_SOGUTMA_SUYU': {'fonksiyon_adi': 'SOĞUTMA SUYU ALMA HATTI',
                      'fonksiyon_kodu': '117104',
                      'geometri': 'LINE',
                      'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                      'ust_grup_id': '117000'},
 'HAT_TRIYAJ': {'fonksiyon_adi': 'KATAR DÜZENLEME (TRİYAJ) ALANI',
                'fonksiyon_kodu': '104102',
                'geometri': 'LINE',
                'ust_grup_adi': 'DEMİRYOLLARI',
                'ust_grup_id': '104000'},
 'KALDIRIM': {'fonksiyon_adi': 'KALDIRIM',
              'fonksiyon_kodu': '130103',
              'geometri': 'LINE',
              'ust_grup_adi': 'ÖZEL ÇİZGİLER',
              'ust_grup_id': '130000'},
 'KA_1DER_ARK_SIT': {'fonksiyon_adi': '1. DERECE ARKEOLOJİK SİT ALANI',
                     'fonksiyon_kodu': '113001',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_1DER_DGL_SIT': {'fonksiyon_adi': '1. DERECE DOĞAL SİT ALANI',
                     'fonksiyon_kodu': '113002',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_2DER_ARK_SIT': {'fonksiyon_adi': '2. DERECE ARKEOLOJİK SİT ALANI',
                     'fonksiyon_kodu': '113003',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_2DER_DGL_SIT': {'fonksiyon_adi': '2. DERECE DOĞAL SİT ALANI',
                     'fonksiyon_kodu': '113004',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_3DER_ARK_SIT': {'fonksiyon_adi': '3. DERECE ARKEOLOJİK SİT ALANI',
                     'fonksiyon_kodu': '113005',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_3DER_DGL_SIT': {'fonksiyon_adi': '3. DERECE DOĞAL SİT ALANI',
                     'fonksiyon_kodu': '113006',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'KA_EKOLOJIK_KORU': {'fonksiyon_adi': 'EKOLOJİK NİTELİĞİ KORUNACAK ALAN',
                      'fonksiyon_kodu': '113007',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'KORUNACAK ALANLAR',
                      'ust_grup_id': '113000'},
 'KA_ENDEMIK_BIYOTOP': {'fonksiyon_adi': 'HASSAS ENDEMİK BİYOTOP ALANI',
                        'fonksiyon_kodu': '113008',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KORUNACAK ALANLAR',
                        'ust_grup_id': '113000'},
 'KA_FLORA_FAUNA': {'fonksiyon_adi': 'KORUNMASI GEREKLİ FLORA VE FAUNA ALANI',
                    'fonksiyon_kodu': '113009',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KORUNACAK ALANLAR',
                    'ust_grup_id': '113000'},
 'KA_KENTSEL_SIT': {'fonksiyon_adi': 'KENTSEL SİT ALANI',
                    'fonksiyon_kodu': '113010',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KORUNACAK ALANLAR',
                    'ust_grup_id': '113000'},
 'KA_KESIN_KOR_HAS': {'fonksiyon_adi': 'KESİN KORUNACAK HASSAS ALAN',
                      'fonksiyon_kodu': '113011',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'KORUNACAK ALANLAR',
                      'ust_grup_id': '113000'},
 'KA_NITELIKLI_DOG_KOR': {'fonksiyon_adi': 'NİTELİKLİ DOĞAL KORUMA ALANI',
                          'fonksiyon_kodu': '113012',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KORUNACAK ALANLAR',
                          'ust_grup_id': '113000'},
 'KA_OCK_A': {'fonksiyon_adi': 'ÖÇK BÖLGESİ HASSAS ALAN (A)',
              'fonksiyon_kodu': '113013',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'KORUNACAK ALANLAR',
              'ust_grup_id': '113000'},
 'KA_OCK_B': {'fonksiyon_adi': 'ÖÇK BÖLGESİ HASSAS ALAN (B)',
              'fonksiyon_kodu': '113014',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'KORUNACAK ALANLAR',
              'ust_grup_id': '113000'},
 'KA_OCK_C': {'fonksiyon_adi': 'ÖÇK BÖLGESİ HASSAS ALAN (C)',
              'fonksiyon_kodu': '113015',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'KORUNACAK ALANLAR',
              'ust_grup_id': '113000'},
 'KA_OZEL_CEVRE_KORUMA': {'fonksiyon_adi': 'ÖZEL ÇEVRE KORUMA BÖLGESİ (ÖÇK)',
                          'fonksiyon_kodu': '113016',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KORUNACAK ALANLAR',
                          'ust_grup_id': '113000'},
 'KA_SURDURULEBILIR_KO': {'fonksiyon_adi': 'SÜRDÜRÜLEBİLİR KORUMA VE KONTROLLÜ KULLANIM ALANI',
                          'fonksiyon_kodu': '113017',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KORUNACAK ALANLAR',
                          'ust_grup_id': '113000'},
 'KA_TABIATI_KORUMA': {'fonksiyon_adi': 'TABİATI KORUMA ALANI',
                       'fonksiyon_kodu': '113018',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KORUNACAK ALANLAR',
                       'ust_grup_id': '113000'},
 'KA_TARIHI_SIT': {'fonksiyon_adi': 'TARİHİ SİT ALANI',
                   'fonksiyon_kodu': '113019',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KORUNACAK ALANLAR',
                   'ust_grup_id': '113000'},
 'KA_ULUSLARARASI_KOR': {'fonksiyon_adi': 'ULUSLARARASI SÖZLEŞMELERLE BELİRLENEN KORUMA ALAN '
                                          'SINIRI',
                         'fonksiyon_kodu': '113020',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'KORUNACAK ALANLAR',
                         'ust_grup_id': '113000'},
 'KA_YABAN_HAYATI_KORU': {'fonksiyon_adi': 'YABAN HAYATI KORUMA VE GELİŞTİRME ALANI',
                          'fonksiyon_kodu': '113021',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KORUNACAK ALANLAR',
                          'ust_grup_id': '113000'},
 'KA_YOR_MIMARI_KORU': {'fonksiyon_adi': 'YÖRESEL MİMARİ ÖZELLİKLERİ KORUNACAK ALAN',
                        'fonksiyon_kodu': '113022',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KORUNACAK ALANLAR',
                        'ust_grup_id': '113000'},
 'KST_ASKERI_YASAK': {'fonksiyon_adi': 'ASKERİ YASAK VE GÜVENLİK BÖLGESİ',
                      'fonksiyon_kodu': '114001',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                      'ust_grup_id': '114000'},
 'KST_BORU_HATTI_KORU': {'fonksiyon_adi': 'BORU HATTI KORUMA KUŞAĞI',
                         'fonksiyon_kodu': '119001',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                         'ust_grup_id': '119000'},
 'KST_DEMIRYOLU_KORU': {'fonksiyon_adi': 'DEMİRYOLLARI KORUMA KUŞAĞI',
                        'fonksiyon_kodu': '119002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                        'ust_grup_id': '119000'},
 'KST_ENERJI_NAKIL_HAT': {'fonksiyon_adi': 'ENERJİ NAKİL HATTI KORUMA KUŞAĞI',
                          'fonksiyon_kodu': '119003',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_HAVAALANI_KORUMA': {'fonksiyon_adi': 'HAVAALANI/HAVALİMANI KORUMA KUŞAĞI',
                          'fonksiyon_kodu': '119005',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_HAVA_KORIDORU': {'fonksiyon_adi': 'HAVA ALANI HAVA KORİDORU',
                       'fonksiyon_kodu': '119004',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                       'ust_grup_id': '119000'},
 'KST_HEYELAN': {'fonksiyon_adi': 'HEYELAN ALANI',
                 'fonksiyon_kodu': '102001',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'AFET TEHLİKELİ ALANLAR',
                 'ust_grup_id': '102000'},
 'KST_ICME_SUYU_KORU': {'fonksiyon_adi': 'İÇME SUYU ANA İLETİM HATTI KORUMA KUŞAĞI',
                        'fonksiyon_kodu': '119006',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                        'ust_grup_id': '119000'},
 'KST_JEOTERMAL_KORU': {'fonksiyon_adi': 'JEOTERMAL KORUMA KUŞAĞI',
                        'fonksiyon_kodu': '119007',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                        'ust_grup_id': '119000'},
 'KST_KARAYOLU_KORUMA': {'fonksiyon_adi': 'KARAYOLLARI YOL KENARI KORUMA KUŞAĞI',
                         'fonksiyon_kodu': '119008',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                         'ust_grup_id': '119000'},
 'KST_KORUMA_KISA': {'fonksiyon_adi': 'İÇME VE KULLANMA SUYU KISA MESAFELİ KORUMA ALANI',
                     'fonksiyon_kodu': '119009',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                     'ust_grup_id': '119000'},
 'KST_KORUMA_MUTLAK': {'fonksiyon_adi': 'İÇME VE KULLANMA SUYU MUTLAK KORUMA ALANI',
                       'fonksiyon_kodu': '119010',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                       'ust_grup_id': '119000'},
 'KST_KORUMA_ORTA': {'fonksiyon_adi': 'İÇME VE KULLANMA SUYU ORTA MESAFELİ KORUMA ALANI',
                     'fonksiyon_kodu': '119011',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                     'ust_grup_id': '119000'},
 'KST_KORUMA_UZUN': {'fonksiyon_adi': 'İÇME VE KULLANMA SUYU UZUN MESAFELİ KORUMA ALANI',
                     'fonksiyon_kodu': '119012',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                     'ust_grup_id': '119000'},
 'KST_NUKLEER_EN_KORU': {'fonksiyon_adi': 'NÜKLEER ENERJİ ÜRETİM ALANI KORUMA KUŞAĞI',
                         'fonksiyon_kodu': '119013',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                         'ust_grup_id': '119000'},
 'KST_ONLEMLI_ALAN': {'fonksiyon_adi': 'ÖNLEMLİ ALAN',
                      'fonksiyon_kodu': '102002',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'AFET TEHLİKELİ ALANLAR',
                      'ust_grup_id': '102000'},
 'KST_SAGLIK_KORUMA': {'fonksiyon_adi': 'SAĞLIK KORUMA BANDI',
                       'fonksiyon_kodu': '119014',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                       'ust_grup_id': '119000'},
 'KST_SULAK_ALAN_BOLGE': {'fonksiyon_adi': 'SULAK ALAN BÖLGESİ',
                          'fonksiyon_kodu': '119016',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_SULAK_EKO_ETKI': {'fonksiyon_adi': 'SULAK ALAN EKOLOJİK ETKİLENME BÖLGESİ',
                        'fonksiyon_kodu': '119017',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                        'ust_grup_id': '119000'},
 'KST_SULAK_MUTLAK': {'fonksiyon_adi': 'SULAK ALAN MUTLAK KORUMA BÖLGESİ',
                      'fonksiyon_kodu': '119018',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                      'ust_grup_id': '119000'},
 'KST_SULAK_OZEL_HUKUM': {'fonksiyon_adi': 'SULAK ALAN ÖZEL HÜKÜM BÖLGESİ',
                          'fonksiyon_kodu': '119019',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_SULAK_TAMPON': {'fonksiyon_adi': 'SULAK ALAN TAMPON BÖLGESİ',
                      'fonksiyon_kodu': '119020',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                      'ust_grup_id': '119000'},
 'KST_SU_KANAL_KORUMA': {'fonksiyon_adi': 'SU KANALLARI KORUMA KUŞAĞI',
                         'fonksiyon_kodu': '119015',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                         'ust_grup_id': '119000'},
 'KST_TASKIN': {'fonksiyon_adi': 'TAŞKINA MARUZ ALAN',
                'fonksiyon_kodu': '102003',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'AFET TEHLİKELİ ALANLAR',
                'ust_grup_id': '102000'},
 'KST_YANICI_PATLAYICI': {'fonksiyon_adi': 'YANICI PARLAYICI VE PATLAYICI MADDELER KORUMA KUŞAĞI',
                          'fonksiyon_kodu': '119021',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_YAPI_YASAK': {'fonksiyon_adi': 'YAPI YASAKLI ALAN',
                    'fonksiyon_kodu': '102004',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'AFET TEHLİKELİ ALANLAR',
                    'ust_grup_id': '102000'},
 'KST_YERALTI_SUYU_KOR': {'fonksiyon_adi': 'YER ALTI SU KAYNAKLARI KORUMA KUŞAĞI',
                          'fonksiyon_kodu': '119022',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'KST_YSK_KORUMA_ALANI': {'fonksiyon_adi': 'YER ALTI SU KAYNAKLARI KORUMA ALANLARI',
                          'fonksiyon_kodu': '119023',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                          'ust_grup_id': '119000'},
 'PL_ACIK_SPOR_TES': {'fonksiyon_adi': 'AÇIK SPOR TESİSİ ALANI',
                      'fonksiyon_kodu': '116001',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                      'ust_grup_id': '116000'},
 'PL_AGACLANDIRILACAK': {'fonksiyon_adi': 'AĞAÇLANDIRILACAK ALAN',
                         'fonksiyon_kodu': '101001',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                         'ust_grup_id': '101000'},
 'PL_AILE_SAGL_MER': {'fonksiyon_adi': 'AİLE SAĞLIĞI MERKEZİ',
                      'fonksiyon_kodu': '115001',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'SAĞLIK TESİSLERİ ALANI',
                      'ust_grup_id': '115000'},
 'PL_AKARYAKIT_DEPO': {'fonksiyon_adi': 'AKARYAKIT ÜRÜNLERİ DEPOLAMA ALANI',
                       'fonksiyon_kodu': '106001',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                       'ust_grup_id': '106000'},
 'PL_AKDENIZ_FOKU_YASA': {'fonksiyon_adi': 'AKDENİZ FOKU YAŞAM ALANI',
                          'fonksiyon_kodu': '103001',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK '
                                          'ALANLAR',
                          'ust_grup_id': '103000'},
 'PL_ANAOKULU': {'fonksiyon_adi': 'ANAOKULU ALANI',
                 'fonksiyon_kodu': '105001',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                 'ust_grup_id': '105000'},
 'PL_ANA_ISTASYON': {'fonksiyon_adi': 'ANA İSTASYON (GAR)',
                     'fonksiyon_kodu': '104001',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'DEMİRYOLLARI',
                     'ust_grup_id': '104000'},
 'PL_APART_OTEL': {'fonksiyon_adi': 'APART OTEL ALANI',
                   'fonksiyon_kodu': '118001',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'TURİZM ALANLARI',
                   'ust_grup_id': '118000'},
 'PL_ARA_ISTASYON': {'fonksiyon_adi': 'ARA İSTASYON',
                     'fonksiyon_kodu': '104002',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'DEMİRYOLLARI',
                     'ust_grup_id': '104000'},
 'PL_ARBORETUM_ALANI': {'fonksiyon_adi': 'ARBORETUM - BOTANİK PARKI',
                        'fonksiyon_kodu': '101002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                        'ust_grup_id': '101000'},
 'PL_ASKERI_ALAN': {'fonksiyon_adi': 'ASKERİ ALAN',
                    'fonksiyon_kodu': '110001',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                    'ust_grup_id': '110000'},
 'PL_ATIKSU_TESISI': {'fonksiyon_adi': 'ATIKSU TESİSLERİ ALANI (ARITMA, TERFİ MERKEZİ)',
                      'fonksiyon_kodu': '117001',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                      'ust_grup_id': '117000'},
 'PL_BAKIM_AKARYAKIT': {'fonksiyon_adi': 'AKARYAKIT VE SERVİS İSTASYONU ALANI',
                        'fonksiyon_kodu': '110002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                        'ust_grup_id': '110000'},
 'PL_BALIKCI_BARINAK': {'fonksiyon_adi': 'BALIKÇI BARINAĞI',
                        'fonksiyon_kodu': '120001',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'DENİZYOLLARI',
                        'ust_grup_id': '120000'},
 'PL_BARINAK': {'fonksiyon_adi': 'BARINAK',
                'fonksiyon_kodu': '120002',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'DENİZYOLLARI',
                'ust_grup_id': '120000'},
 'PL_BETON_SANTRALI': {'fonksiyon_adi': 'BETON SANTRALİ',
                       'fonksiyon_kodu': '110003',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                       'ust_grup_id': '110000'},
 'PL_BHA': {'fonksiyon_adi': 'BELEDİYE HİZMET ALANI',
            'fonksiyon_kodu': '110004',
            'geometri': 'POLYGON',
            'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
            'ust_grup_id': '110000'},
 'PL_BISIKLET_PARKI': {'fonksiyon_adi': 'BİSİKLET PARKI',
                       'fonksiyon_kodu': '109001',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KARAYOLLARI',
                       'ust_grup_id': '109000'},
 'PL_CAMI': {'fonksiyon_adi': 'CAMİ',
             'fonksiyon_kodu': '108001',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'İBADET ALANLARI',
             'ust_grup_id': '108000'},
 'PL_CEKEK_YERI': {'fonksiyon_adi': 'TEKNE İMAL VE ÇEKEK YERİ',
                   'fonksiyon_kodu': '120003',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'DENİZYOLLARI',
                   'ust_grup_id': '120000'},
 'PL_COCUK_BAHCESI': {'fonksiyon_adi': 'ÇOCUK BAHÇESİ VE OYUN ALANI',
                      'fonksiyon_kodu': '101003',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                      'ust_grup_id': '101000'},
 'PL_DENIZ_KAPLM_KORU': {'fonksiyon_adi': 'DENİZ KAPLUMBAĞALARI ÜREME VE KORUMA ALANI',
                         'fonksiyon_kodu': '103002',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK '
                                         'ALANLAR',
                         'ust_grup_id': '103000'},
 'PL_DEPOLAMA': {'fonksiyon_adi': 'DEPOLAMA ALANI',
                 'fonksiyon_kodu': '110005',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                 'ust_grup_id': '110000'},
 'PL_DOGALGAZ_DAGITIM': {'fonksiyon_adi': 'DOĞALGAZ / DAĞITIM TESİSİ ALANI',
                         'fonksiyon_kodu': '106002',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                         'ust_grup_id': '106000'},
 'PL_DOGAL_KARKT_KORU': {'fonksiyon_adi': 'DOĞAL KARAKTERİ KORUNACAK ALAN',
                         'fonksiyon_kodu': '103003',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK '
                                         'ALANLAR',
                         'ust_grup_id': '103000'},
 'PL_DOLFEN_PLATFORM': {'fonksiyon_adi': 'DOLFEN/PLATFORM',
                        'fonksiyon_kodu': '120004',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'DENİZYOLLARI',
                        'ust_grup_id': '120000'},
 'PL_ENDUSTRIYEL_GEL': {'fonksiyon_adi': 'ENDÜSTRİYEL GELİŞME BÖLGESİ',
                        'fonksiyon_kodu': '110006',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                        'ust_grup_id': '110000'},
 'PL_ENDUSTRI_BOL': {'fonksiyon_adi': 'ENDÜSTRİ BÖLGESİ',
                     'fonksiyon_kodu': '114002',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                     'ust_grup_id': '114000'},
 'PL_ENERJI_DEPOLAMA': {'fonksiyon_adi': 'ENERJİ DEPOLAMA ALANI',
                        'fonksiyon_kodu': '106100',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                        'ust_grup_id': '106000'},
 'PL_ENERJI_URETIM': {'fonksiyon_adi': 'ENERJİ ÜRETİM ALANI',
                      'fonksiyon_kodu': '106003',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                      'ust_grup_id': '106000'},
 'PL_FUAR': {'fonksiyon_adi': 'FUAR, PANAYIR VE FESTİVAL ALANI',
             'fonksiyon_kodu': '101004',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
             'ust_grup_id': '101000'},
 'PL_GELISME_KONUT': {'fonksiyon_adi': 'GELİŞME KONUT ALANI',
                      'fonksiyon_kodu': '112001',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'KONUT ALANLARI / YERLEŞİM ALANLARI',
                      'ust_grup_id': '112000'},
 'PL_GEMI_SOKUM': {'fonksiyon_adi': 'GEMİ SÖKÜM YERİ',
                   'fonksiyon_kodu': '120005',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'DENİZYOLLARI',
                   'ust_grup_id': '120000'},
 'PL_GOLF_ALANI': {'fonksiyon_adi': 'GOLF ALANI',
                   'fonksiyon_kodu': '118002',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'TURİZM ALANLARI',
                   'ust_grup_id': '118000'},
 'PL_GUNUBIRLIK_TESIS': {'fonksiyon_adi': 'GÜNÜBİRLİK TESİS ALANI',
                         'fonksiyon_kodu': '118003',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'TURİZM ALANLARI',
                         'ust_grup_id': '118000'},
 'PL_HABERLESME_ALTYPI': {'fonksiyon_adi': 'ELEKTRONİK HABERLEŞME ALTYAPI ALANI',
                          'fonksiyon_kodu': '106004',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                          'ust_grup_id': '106000'},
 'PL_HALK_EGITIM': {'fonksiyon_adi': 'HALK EĞİTİM MERKEZİ',
                    'fonksiyon_kodu': '105002',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                    'ust_grup_id': '105000'},
 'PL_HASTANE': {'fonksiyon_adi': 'HASTANE',
                'fonksiyon_kodu': '115002',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'SAĞLIK TESİSLERİ ALANI',
                'ust_grup_id': '115000'},
 'PL_HAVAALANI': {'fonksiyon_adi': 'HAVAALANI/HAVALİMANI',
                  'fonksiyon_kodu': '107001',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'HAVAYOLLARI',
                  'ust_grup_id': '107000'},
 'PL_HAVAI': {'fonksiyon_adi': 'HAVAİ HAT İSTASYONU',
              'fonksiyon_kodu': '111001',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
              'ust_grup_id': '111000'},
 'PL_HAVARAY_ISTASYONU': {'fonksiyon_adi': 'HAVARAY İSTASYONU',
                          'fonksiyon_kodu': '111002',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
                          'ust_grup_id': '111000'},
 'PL_HAYVANAT_BAHCESI': {'fonksiyon_adi': 'HAYVANAT BAHÇESİ',
                         'fonksiyon_kodu': '101005',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                         'ust_grup_id': '101000'},
 'PL_HELIKOPTER_INIS': {'fonksiyon_adi': 'HELİKOPTER İNİŞ ALANI',
                        'fonksiyon_kodu': '107002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'HAVAYOLLARI',
                        'ust_grup_id': '107000'},
 'PL_HIPODROM': {'fonksiyon_adi': 'HİPODROM',
                 'fonksiyon_kodu': '101006',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                 'ust_grup_id': '101000'},
 'PL_HOSTEL_ALANI': {'fonksiyon_adi': 'HOSTEL ALANI',
                     'fonksiyon_kodu': '118004',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'TURİZM ALANLARI',
                     'ust_grup_id': '118000'},
 'PL_ICME_SUYU_TESIS': {'fonksiyon_adi': 'İÇME SUYU TESİSLERİ ALANI (DEPOLAMA, ARITMA, TERFİ '
                                         'MERKEZİ)',
                        'fonksiyon_kodu': '117002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                        'ust_grup_id': '117000'},
 'PL_IHA': {'fonksiyon_adi': 'İDARİ HİZMET ALANI',
            'fonksiyon_kodu': '110007',
            'geometri': 'POLYGON',
            'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
            'ust_grup_id': '110000'},
 'PL_ILKOKUL_ALANI': {'fonksiyon_adi': 'İLKOKUL ALANI',
                      'fonksiyon_kodu': '105003',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                      'ust_grup_id': '105000'},
 'PL_IMALATHANE': {'fonksiyon_adi': 'İMALATHANE TESİS ALANI',
                   'fonksiyon_kodu': '110008',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                   'ust_grup_id': '110000'},
 'PL_INIS_RAMPA': {'fonksiyon_adi': 'DENİZ İNİŞ RAMPASI',
                   'fonksiyon_kodu': '120006',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'DENİZYOLLARI',
                   'ust_grup_id': '120000'},
 'PL_ISKELE': {'fonksiyon_adi': 'İSKELE',
               'fonksiyon_kodu': '120007',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'DENİZYOLLARI',
               'ust_grup_id': '120000'},
 'PL_KAMPING_ALANI': {'fonksiyon_adi': 'KAMPİNG ALANI',
                      'fonksiyon_kodu': '118005',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'TURİZM ALANLARI',
                      'ust_grup_id': '118000'},
 'PL_KAPALI_SPOR_TES': {'fonksiyon_adi': 'KAPALI SPOR TESİSİ ALANI',
                        'fonksiyon_kodu': '116002',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                        'ust_grup_id': '116000'},
 'PL_KATI_ATIK_TESISI': {'fonksiyon_adi': 'KATI ATIK TESİSLERİ ALANI (BOŞALTMA, BERTARAF, İŞLEME, '
                                          'TRANSFER VE DEPOLAMA)',
                         'fonksiyon_kodu': '117003',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                         'ust_grup_id': '117000'},
 'PL_KENT_ORMANI': {'fonksiyon_adi': 'KENT ORMANI',
                    'fonksiyon_kodu': '101007',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                    'ust_grup_id': '101000'},
 'PL_KILISE': {'fonksiyon_adi': 'KİLİSE',
               'fonksiyon_kodu': '108002',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'İBADET ALANLARI',
               'ust_grup_id': '108000'},
 'PL_KIS_SPORLARI': {'fonksiyon_adi': 'KIŞ SPORLARI VE KAYAK TESİSİ ALANI',
                     'fonksiyon_kodu': '118006',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'TURİZM ALANLARI',
                     'ust_grup_id': '118000'},
 'PL_KIYI_KORUMA': {'fonksiyon_adi': 'KIYI KORUMA YAPILARI',
                    'fonksiyon_kodu': '120008',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'DENİZYOLLARI',
                    'ust_grup_id': '120000'},
 'PL_KONGRE_SERGI': {'fonksiyon_adi': 'KONGRE VE SERGİ MERKEZİ ALANI',
                     'fonksiyon_kodu': '116003',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                     'ust_grup_id': '116000'},
 'PL_KONTEYNER_LIMAN': {'fonksiyon_adi': 'KONTEYNER LİMANI',
                        'fonksiyon_kodu': '120009',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'DENİZYOLLARI',
                        'ust_grup_id': '120000'},
 'PL_KONUT': {'fonksiyon_adi': 'YERLEŞİK KONUT ALANI',
              'fonksiyon_kodu': '112002',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'KONUT ALANLARI / YERLEŞİM ALANLARI',
              'ust_grup_id': '112000'},
 'PL_KONUT_TICARET': {'fonksiyon_adi': 'TİCARET - KONUT ALANI',
                      'fonksiyon_kodu': '110009',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                      'ust_grup_id': '110000'},
 'PL_KORUNACAK_BAHCE': {'fonksiyon_adi': 'KORUNACAK BAHÇE',
                        'fonksiyon_kodu': '101008',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                        'ust_grup_id': '101000'},
 'PL_KRES_BAKIMEVI': {'fonksiyon_adi': 'KREŞ, GÜNDÜZ BAKIMEVİ',
                      'fonksiyon_kodu': '116004',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                      'ust_grup_id': '116000'},
 'PL_KRUVAZIYER_LIMAN': {'fonksiyon_adi': 'KRUVAZİYER LİMANI',
                         'fonksiyon_kodu': '120010',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'DENİZYOLLARI',
                         'ust_grup_id': '120000'},
 'PL_KUCUK_SANAYI': {'fonksiyon_adi': 'KÜÇÜK SANAYİ ALANI',
                     'fonksiyon_kodu': '110010',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                     'ust_grup_id': '110000'},
 'PL_KULTUREL_TESIS': {'fonksiyon_adi': 'KÜLTÜREL TESİS ALANI',
                       'fonksiyon_kodu': '116005',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                       'ust_grup_id': '116000'},
 'PL_KUMSAL_PLAJ': {'fonksiyon_adi': 'KUMSAL-PLAJ',
                    'fonksiyon_kodu': '103004',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                    'ust_grup_id': '103000'},
 'PL_LISE_ALANI': {'fonksiyon_adi': 'LİSE ALANI',
                   'fonksiyon_kodu': '105004',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                   'ust_grup_id': '105000'},
 'PL_LOJISTIK_TESIS': {'fonksiyon_adi': 'LOJİSTİK TESİS ALANI',
                       'fonksiyon_kodu': '110011',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                       'ust_grup_id': '110000'},
 'PL_MAHMUZ': {'fonksiyon_adi': 'MAHMUZ',
               'fonksiyon_kodu': '120011',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'DENİZYOLLARI',
               'ust_grup_id': '120000'},
 'PL_MAKI_FUNDA': {'fonksiyon_adi': 'MAKİLİK- FUNDALIK ALAN',
                   'fonksiyon_kodu': '103005',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                   'ust_grup_id': '103000'},
 'PL_MENFEZ': {'fonksiyon_adi': 'MENFEZ',
               'fonksiyon_kodu': '120012',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'DENİZYOLLARI',
               'ust_grup_id': '120000'},
 'PL_MERA_ALANI': {'fonksiyon_adi': 'MERA ALANI',
                   'fonksiyon_kodu': '103006',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                   'ust_grup_id': '103000'},
 'PL_MESCIT': {'fonksiyon_adi': 'MESCİT',
               'fonksiyon_kodu': '108003',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'İBADET ALANLARI',
               'ust_grup_id': '108000'},
 'PL_MESIRE_YERI': {'fonksiyon_adi': 'MESİRE YERİ',
                    'fonksiyon_kodu': '101009',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                    'ust_grup_id': '101000'},
 'PL_MEYDAN': {'fonksiyon_adi': 'MEYDAN',
               'fonksiyon_kodu': '101010',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
               'ust_grup_id': '101000'},
 'PL_MEZARLIK': {'fonksiyon_adi': 'MEZARLIK ALANI',
                 'fonksiyon_kodu': '101011',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                 'ust_grup_id': '101000'},
 'PL_MILLET_BAHCESI': {'fonksiyon_adi': 'MİLLET BAHÇESİ',
                       'fonksiyon_kodu': '101012',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                       'ust_grup_id': '101000'},
 'PL_MILLI_PARK': {'fonksiyon_adi': 'MİLLİ PARK',
                   'fonksiyon_kodu': '113023',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KORUNACAK ALANLAR',
                   'ust_grup_id': '113000'},
 'PL_MOTEL_ALANI': {'fonksiyon_adi': 'MOTEL ALANI',
                    'fonksiyon_kodu': '118007',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'TURİZM ALANLARI',
                    'ust_grup_id': '118000'},
 'PL_NUKLEER_SANTRAL': {'fonksiyon_adi': 'NÜKLEER ENERJİ SANTRALİ ALANI',
                        'fonksiyon_kodu': '106005',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                        'ust_grup_id': '106000'},
 'PL_ORGANIK_TARIM': {'fonksiyon_adi': 'ORGANİK TARIM ALANI',
                      'fonksiyon_kodu': '103007',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                      'ust_grup_id': '103000'},
 'PL_ORMAN_ALANI': {'fonksiyon_adi': 'ORMAN ALANI',
                    'fonksiyon_kodu': '103008',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                    'ust_grup_id': '103000'},
 'PL_ORTAOKUL_ALANI': {'fonksiyon_adi': 'ORTAOKUL ALANI',
                       'fonksiyon_kodu': '105005',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                       'ust_grup_id': '105000'},
 'PL_ORTU_ALTI_TARIM': {'fonksiyon_adi': 'ÖRTÜ ALTI TARIM ARAZİSİ',
                        'fonksiyon_kodu': '103009',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK '
                                        'ALANLAR',
                        'ust_grup_id': '103000'},
 'PL_OSB': {'fonksiyon_adi': 'ORGANİZE SANAYİ BÖLGESİ',
            'fonksiyon_kodu': '114003',
            'geometri': 'POLYGON',
            'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
            'ust_grup_id': '114000'},
 'PL_OTEL_ALANI': {'fonksiyon_adi': 'OTEL ALANI',
                   'fonksiyon_kodu': '118008',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'TURİZM ALANLARI',
                   'ust_grup_id': '118000'},
 'PL_OTOGAR': {'fonksiyon_adi': 'TERMİNAL (OTOGAR)',
               'fonksiyon_kodu': '109002',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'KARAYOLLARI',
               'ust_grup_id': '109000'},
 'PL_OTOPARK': {'fonksiyon_adi': 'GENEL OTOPARK ALANI',
                'fonksiyon_kodu': '109003',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'KARAYOLLARI',
                'ust_grup_id': '109000'},
 'PL_OZEL_ANAOKULU': {'fonksiyon_adi': 'ÖZEL ANAOKULU ALANI',
                      'fonksiyon_kodu': '105006',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                      'ust_grup_id': '105000'},
 'PL_OZEL_EGITIM': {'fonksiyon_adi': 'ÖZEL EĞİTİM ALANI',
                    'fonksiyon_kodu': '105007',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                    'ust_grup_id': '105000'},
 'PL_OZEL_SAGLIK_TES': {'fonksiyon_adi': 'ÖZEL SAĞLIK TESİSİ ALANI',
                        'fonksiyon_kodu': '115003',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SAĞLIK TESİSLERİ ALANI',
                        'ust_grup_id': '115000'},
 'PL_OZEL_SOSYAL_TESIS': {'fonksiyon_adi': 'ÖZEL SOSYAL TESİS ALANI',
                          'fonksiyon_kodu': '116011',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                          'ust_grup_id': '116000'},
 'PL_OZEL_YURT_ALANI': {'fonksiyon_adi': 'ÖZEL YURT ALANI',
                        'fonksiyon_kodu': '116012',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                        'ust_grup_id': '116000'},
 'PL_O_ACIK_SPOR_TES': {'fonksiyon_adi': 'ÖZEL AÇIK SPOR TESİSİ ALANI',
                        'fonksiyon_kodu': '116006',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                        'ust_grup_id': '116000'},
 'PL_O_KAPALI_SPOR_TES': {'fonksiyon_adi': 'ÖZEL KAPALI SPOR TESİSİ ALANI',
                          'fonksiyon_kodu': '116007',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                          'ust_grup_id': '116000'},
 'PL_O_KRES_BAKIMEVI': {'fonksiyon_adi': 'ÖZEL KREŞ, GÜNDÜZ BAKIMEVİ',
                        'fonksiyon_kodu': '116008',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                        'ust_grup_id': '116000'},
 'PL_O_KULTUREL_TESIS': {'fonksiyon_adi': 'ÖZEL KÜLTÜREL TESİS ALANI',
                         'fonksiyon_kodu': '116009',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                         'ust_grup_id': '116000'},
 'PL_PANSIYON_ALANI': {'fonksiyon_adi': 'PANSİYON ALANI',
                       'fonksiyon_kodu': '118009',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'TURİZM ALANLARI',
                       'ust_grup_id': '118000'},
 'PL_PARK': {'fonksiyon_adi': 'PARK',
             'fonksiyon_kodu': '101013',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
             'ust_grup_id': '101000'},
 'PL_PASIF_YESIL': {'fonksiyon_adi': 'PASİF YEŞİL ALAN',
                    'fonksiyon_kodu': '101014',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                    'ust_grup_id': '101000'},
 'PL_PAZAR_ALANI': {'fonksiyon_adi': 'PAZAR ALANI',
                    'fonksiyon_kodu': '110012',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                    'ust_grup_id': '110000'},
 'PL_RAY_ISTASYON': {'fonksiyon_adi': 'RAYLI TOPLU TAŞIMA İSTASYONU',
                     'fonksiyon_kodu': '111003',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
                     'ust_grup_id': '111000'},
 'PL_REGULATOR_ALANI': {'fonksiyon_adi': 'REGÜLATÖR ALANI',
                        'fonksiyon_kodu': '106006',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                        'ust_grup_id': '106000'},
 'PL_REKREASYON': {'fonksiyon_adi': 'REKREASYON ALANI',
                   'fonksiyon_kodu': '101015',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                   'ust_grup_id': '101000'},
 'PL_REKREATIF_ALAN': {'fonksiyon_adi': 'REKREAKTİF ALAN',
                       'fonksiyon_kodu': '101016',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                       'ust_grup_id': '101000'},
 'PL_RESMI_KURUM': {'fonksiyon_adi': 'RESMİ KURUM ALANI',
                    'fonksiyon_kodu': '110013',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                    'ust_grup_id': '110000'},
 'PL_RIHTIM': {'fonksiyon_adi': 'RIHTIM',
               'fonksiyon_kodu': '120013',
               'geometri': 'POLYGON',
               'ust_grup_adi': 'DENİZYOLLARI',
               'ust_grup_id': '120000'},
 'PL_RO_RO_LIMAN': {'fonksiyon_adi': 'RO RO LİMANI',
                    'fonksiyon_kodu': '120014',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'DENİZYOLLARI',
                    'ust_grup_id': '120000'},
 'PL_SAGLIK_TATIL_KOYU': {'fonksiyon_adi': 'SAĞLIK ODAKLI TATİL KÖYÜ',
                          'fonksiyon_kodu': '118010',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'TURİZM ALANLARI',
                          'ust_grup_id': '118000'},
 'PL_SAGLIK_TESISI': {'fonksiyon_adi': 'SAĞLIK TESİSİ ALANI',
                      'fonksiyon_kodu': '115004',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'SAĞLIK TESİSLERİ ALANI',
                      'ust_grup_id': '115000'},
 'PL_SANAYI_TESIS': {'fonksiyon_adi': 'SANAYİ TESİS ALANI',
                     'fonksiyon_kodu': '110014',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                     'ust_grup_id': '110000'},
 'PL_SAPEL': {'fonksiyon_adi': 'ŞAPEL',
              'fonksiyon_kodu': '108004',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'İBADET ALANLARI',
              'ust_grup_id': '108000'},
 'PL_SEFKAT_EVI': {'fonksiyon_adi': 'ŞEFKAT EVLERİ ALANI',
                   'fonksiyon_kodu': '116013',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                   'ust_grup_id': '116000'},
 'PL_SERBEST_BOLGE': {'fonksiyon_adi': 'SERBEST BÖLGE',
                      'fonksiyon_kodu': '114004',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                      'ust_grup_id': '114000'},
 'PL_SEYIR_TERASI': {'fonksiyon_adi': 'BAKI VE SEYİR TERASI',
                     'fonksiyon_kodu': '101017',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'AÇIK VE YEŞİL ALANLAR',
                     'ust_grup_id': '101000'},
 'PL_SINAGOG': {'fonksiyon_adi': 'SİNAGOG (HAVRA)',
                'fonksiyon_kodu': '108005',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'İBADET ALANLARI',
                'ust_grup_id': '108000'},
 'PL_SOSYAL_TESIS': {'fonksiyon_adi': 'SOSYAL TESİS ALANI',
                     'fonksiyon_kodu': '116014',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                     'ust_grup_id': '116000'},
 'PL_SU_KAY_TOPLAMA': {'fonksiyon_adi': 'SU KAYNAKLARI TOPLAMA YERİ (KAPTAJ ALANI)',
                       'fonksiyon_kodu': '117004',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                       'ust_grup_id': '117000'},
 'PL_SU_URUNLERI': {'fonksiyon_adi': 'SU ÜRÜNLERİ ÜRETİM VE YETİŞTİRME TESİSİ',
                    'fonksiyon_kodu': '110015',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                    'ust_grup_id': '110000'},
 'PL_SU_YUZEYI': {'fonksiyon_adi': 'SU YÜZEYİ',
                  'fonksiyon_kodu': '117005',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                  'ust_grup_id': '117000'},
 'PL_TABIAT_PARKI': {'fonksiyon_adi': 'TABİAT PARKI ALANI',
                     'fonksiyon_kodu': '113024',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'PL_TARIMSAL_ALAN': {'fonksiyon_adi': 'TARIMSAL NİTELİKLİ ALAN',
                      'fonksiyon_kodu': '103010',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK ALANLAR',
                      'ust_grup_id': '103000'},
 'PL_TARIM_HAYVANCILIK': {'fonksiyon_adi': 'TARIM VE HAYVANCILIK TESİS ALANI',
                          'fonksiyon_kodu': '110016',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                          'ust_grup_id': '110000'},
 'PL_TATIL_KOYU': {'fonksiyon_adi': 'TATİL KÖYÜ ALANI',
                   'fonksiyon_kodu': '118011',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'TURİZM ALANLARI',
                   'ust_grup_id': '118000'},
 'PL_TEHLIKELI_ATIK_TE': {'fonksiyon_adi': 'TEHLİKELİ ATIK TESİSLERİ ALANI (BERTARAF VE DEPOLAMA)',
                          'fonksiyon_kodu': '117006',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                          'ust_grup_id': '117000'},
 'PL_TEKNE_IMAL': {'fonksiyon_adi': 'TEKNE İMAL VE BAKIM YERİ',
                   'fonksiyon_kodu': '120015',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'DENİZYOLLARI',
                   'ust_grup_id': '120000'},
 'PL_TEKNIK_ALTYAPI': {'fonksiyon_adi': 'TEKNİK ALTYAPI ALANI',
                       'fonksiyon_kodu': '117007',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                       'ust_grup_id': '117000'},
 'PL_TEKNIK_OGRETIM': {'fonksiyon_adi': 'MESLEKİ VE TEKNİK ÖĞRETİM TESİSİ ALANI',
                       'fonksiyon_kodu': '105008',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                       'ust_grup_id': '105000'},
 'PL_TERMAL_TURIZM': {'fonksiyon_adi': 'TERMAL TURİZM ALANI',
                      'fonksiyon_kodu': '118012',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'TURİZM ALANLARI',
                      'ust_grup_id': '118000'},
 'PL_TERMIK_SANTRAL': {'fonksiyon_adi': 'TERMİK SANTRAL ALANI',
                       'fonksiyon_kodu': '106007',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                       'ust_grup_id': '106000'},
 'PL_TERSANE_ALANI': {'fonksiyon_adi': 'TERSANE ALANI',
                      'fonksiyon_kodu': '120016',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'DENİZYOLLARI',
                      'ust_grup_id': '120000'},
 'PL_TGB': {'fonksiyon_adi': 'TEKNOLOJİ GELİŞTİRME BÖLGESİ',
            'fonksiyon_kodu': '114005',
            'geometri': 'POLYGON',
            'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
            'ust_grup_id': '114000'},
 'PL_TICARET': {'fonksiyon_adi': 'TİCARET ALANI',
                'fonksiyon_kodu': '110018',
                'geometri': 'POLYGON',
                'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                'ust_grup_id': '110000'},
 'PL_TICARET_T1': {'fonksiyon_adi': 'T1 TİCARET ALANI',
                   'fonksiyon_kodu': '110019',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                   'ust_grup_id': '110000'},
 'PL_TICARET_T2': {'fonksiyon_adi': 'T2 TİCARET ALANI',
                   'fonksiyon_kodu': '110020',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                   'ust_grup_id': '110000'},
 'PL_TICARET_T3': {'fonksiyon_adi': 'T3 TİCARET ALANI',
                   'fonksiyon_kodu': '110021',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                   'ust_grup_id': '110000'},
 'PL_TICARET_TURIZM': {'fonksiyon_adi': 'TİCARET - TURİZM ALANI',
                       'fonksiyon_kodu': '110022',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                       'ust_grup_id': '110000'},
 'PL_TIC_TURZM_KNT': {'fonksiyon_adi': 'TİCARET-TURİZM-KONUT ALANI',
                      'fonksiyon_kodu': '110017',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                      'ust_grup_id': '110000'},
 'PL_TIR_PARKI': {'fonksiyon_adi': 'TIR, KAMYON, MAKİNE PARKI VE GARAJ ALANI',
                  'fonksiyon_kodu': '109004',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'KARAYOLLARI',
                  'ust_grup_id': '109000'},
 'PL_TOPLU_ISYERLERI': {'fonksiyon_adi': 'TOPLU İŞYERLERİ',
                        'fonksiyon_kodu': '110023',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                        'ust_grup_id': '110000'},
 'PL_TOPTAN_TICARET': {'fonksiyon_adi': 'TOPTAN TİCARET ALANI',
                       'fonksiyon_kodu': '110024',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'KENTSEL ÇALIŞMA ALANLARI',
                       'ust_grup_id': '110000'},
 'PL_TRAFO_ALANI': {'fonksiyon_adi': 'TRAFO ALANI',
                    'fonksiyon_kodu': '106008',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                    'ust_grup_id': '106000'},
 'PL_TT_AKTARMA': {'fonksiyon_adi': 'TOPLU TAŞINIM TÜRLERİ ARASI DEĞİŞİM VE AKTARMA ALANI',
                   'fonksiyon_kodu': '111004',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KENTSEL TOPLU TAŞIMA GÜZERGAHLARI',
                   'ust_grup_id': '111000'},
 'PL_TURBIN_ALANI': {'fonksiyon_adi': 'TÜRBİN ALANI',
                     'fonksiyon_kodu': '106009',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                     'ust_grup_id': '106000'},
 'PL_YANICI_MADDE_DEPO': {'fonksiyon_adi': 'YANICI PARLAYICI VE PATLAYICI MADDELER ÜRETİM VE DEPO '
                                           'ALANI',
                          'fonksiyon_kodu': '106010',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                          'ust_grup_id': '106000'},
 'PL_YAPAY_ADA': {'fonksiyon_adi': 'YAPAY ADA',
                  'fonksiyon_kodu': '117008',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'SU - ATIKSU VE ATIK SİSTEMLERİ',
                  'ust_grup_id': '117000'},
 'PL_YASLI_BAKIMEVI': {'fonksiyon_adi': 'YAŞLI BAKIMEVİ ALANI',
                       'fonksiyon_kodu': '116015',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                       'ust_grup_id': '116000'},
 'PL_YAT_LIMANI': {'fonksiyon_adi': 'YAT LİMANI',
                   'fonksiyon_kodu': '120017',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'DENİZYOLLARI',
                   'ust_grup_id': '120000'},
 'PL_YENILENEBILIR_EN': {'fonksiyon_adi': 'YENİLENEBİLİR ENERJİ KAYNAKLARINA DAYALI ÜRETİM TESİSİ '
                                          'ALANI',
                         'fonksiyon_kodu': '106011',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'ENERJI ÜRETİM DAĞITIM VE DEPOLAMA',
                         'ust_grup_id': '106000'},
 'PL_YUKSEKOGRETIM': {'fonksiyon_adi': 'YÜKSEK ÖĞRETİM ALANI',
                      'fonksiyon_kodu': '105009',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'EĞİTİM TESİSLERİ ALANI',
                      'ust_grup_id': '105000'},
 'PL_YURT_ALANI': {'fonksiyon_adi': 'YURT ALANI',
                   'fonksiyon_kodu': '116016',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'SOSYAL VE KÜLTÜREL TESİS ALANI',
                   'ust_grup_id': '116000'},
 'PL_ZEYTINLIK_ALAN': {'fonksiyon_adi': 'ZEYTİNLİK ALAN',
                       'fonksiyon_kodu': '103011',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'BUGÜNKÜ ARAZİ KULLANIMI DEVAM ETTİRİLEREK KORUNACAK '
                                       'ALANLAR',
                       'ust_grup_id': '103000'},
 'SNR_BELEDIYE': {'fonksiyon_adi': 'BELEDİYE SINIRI',
                  'fonksiyon_kodu': '121101',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'İDARİ SINIRLAR',
                  'ust_grup_id': '121000'},
 'SNR_BOGAZICI_ETKILNM': {'fonksiyon_adi': 'BOĞAZİÇİ ETKİLENME BÖLGESİ SINIRI',
                          'fonksiyon_kodu': '114103',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                          'ust_grup_id': '114000'},
 'SNR_BOGAZ_GERI_GOR': {'fonksiyon_adi': 'BOĞAZİÇİ GERİ GÖRÜNÜM BÖLGESİ SINIRI',
                        'fonksiyon_kodu': '114101',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                        'ust_grup_id': '114000'},
 'SNR_BOGAZ_ON_GOR': {'fonksiyon_adi': 'BOĞAZİÇİ ÖN GÖRÜNÜM BÖLGESİ SINIRI',
                      'fonksiyon_kodu': '114102',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                      'ust_grup_id': '114000'},
 'SNR_DENIZ_ULASIM': {'fonksiyon_adi': 'DENİZ ULAŞIM BAĞLANTISI',
                      'fonksiyon_kodu': '120101',
                      'geometri': 'LINE',
                      'ust_grup_adi': 'DENİZYOLLARI',
                      'ust_grup_id': '120000'},
 'SNR_DIGER_OZL': {'fonksiyon_adi': 'DİĞER ÖZEL KANUNLARLA BELİRLENEN ALAN SINIRLARI',
                   'fonksiyon_kodu': '114104',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                   'ust_grup_id': '114000'},
 'SNR_ETAPLAMA': {'fonksiyon_adi': 'ETAPLAMA SINIRI',
                  'fonksiyon_kodu': '122103',
                  'geometri': 'POLYGON',
                  'ust_grup_adi': 'PLANLAMA SINIRLARI',
                  'ust_grup_id': '122000'},
 'SNR_GOB': {'fonksiyon_adi': 'GECEKONDU ÖNLEME BÖLGESİ SINIRI',
             'fonksiyon_kodu': '114105',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
             'ust_grup_id': '114000'},
 'SNR_IL': {'fonksiyon_adi': 'İL SINIRI',
            'fonksiyon_kodu': '121102',
            'geometri': 'POLYGON',
            'ust_grup_adi': 'İDARİ SINIRLAR',
            'ust_grup_id': '121000'},
 'SNR_ILCE': {'fonksiyon_adi': 'İLÇE SINIRI',
              'fonksiyon_kodu': '121103',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'İDARİ SINIRLAR',
              'ust_grup_id': '121000'},
 'SNR_IMAR_HAKKI_AKT': {'fonksiyon_adi': 'İMAR HAKKI AKTARIM ALANI SINIRI',
                        'fonksiyon_kodu': '122105',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'PLANLAMA SINIRLARI',
                        'ust_grup_id': '122000'},
 'SNR_KENTSEL_TASARIM': {'fonksiyon_adi': 'KENTSEL TASARIM PROJESİ SINIRI',
                         'fonksiyon_kodu': '122106',
                         'geometri': 'POLYGON',
                         'ust_grup_adi': 'PLANLAMA SINIRLARI',
                         'ust_grup_id': '122000'},
 'SNR_KIYI_KENAR': {'fonksiyon_adi': 'KIYI KENAR ÇİZGİSİ',
                    'fonksiyon_kodu': '114106',
                    'geometri': 'LINE',
                    'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                    'ust_grup_id': '114000'},
 'SNR_KOY': {'fonksiyon_adi': 'KÖY SINIRI',
             'fonksiyon_kodu': '121104',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'İDARİ SINIRLAR',
             'ust_grup_id': '121000'},
 'SNR_MAHALLE': {'fonksiyon_adi': 'MAHALLE SINIRI',
                 'fonksiyon_kodu': '121105',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'İDARİ SINIRLAR',
                 'ust_grup_id': '121000'},
 'SNR_MANIA_PLAN': {'fonksiyon_adi': 'MANİA PLANI',
                    'fonksiyon_kodu': '119101',
                    'geometri': 'LINE',
                    'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                    'ust_grup_id': '119000'},
 'SNR_MUCAVIR': {'fonksiyon_adi': 'MÜCAVİR ALAN SINIRI',
                 'fonksiyon_kodu': '121106',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'İDARİ SINIRLAR',
                 'ust_grup_id': '121000'},
 'SNR_OZEL_PROJE_ALANI': {'fonksiyon_adi': 'ÖZEL PROJE ALANI SINIRI',
                          'fonksiyon_kodu': '122107',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'PLANLAMA SINIRLARI',
                          'ust_grup_id': '122000'},
 'SNR_PLANONAMA': {'fonksiyon_adi': 'PLAN ONAMA SINIRI',
                   'fonksiyon_kodu': '122109',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'PLANLAMA SINIRLARI',
                   'ust_grup_id': '122000'},
 'SNR_PLAN_DEGISIKLIGI': {'fonksiyon_adi': 'PLAN DEĞİŞİKLİĞİ ONAMA SINIRI',
                          'fonksiyon_kodu': '122108',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'PLANLAMA SINIRLARI',
                          'ust_grup_id': '122000'},
 'SNR_SAHIL_SERIDI': {'fonksiyon_adi': 'SAHİL ŞERİDİ',
                      'fonksiyon_kodu': '114200',
                      'geometri': 'POLYGON',
                      'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                      'ust_grup_id': '114000'},
 'SNR_SEG': {'fonksiyon_adi': 'SİT ETKİLEŞİM GEÇİŞ ALANI SINIRI',
             'fonksiyon_kodu': '113101',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'KORUNACAK ALANLAR',
             'ust_grup_id': '113000'},
 'SNR_SULAK_ALAN': {'fonksiyon_adi': 'SULAK ALAN SINIRI',
                    'fonksiyon_kodu': '119102',
                    'geometri': 'POLYGON',
                    'ust_grup_adi': 'YAPI SINIRLAMASI GETİRİLEREK KORUNACAK ALANLAR',
                    'ust_grup_id': '119000'},
 'SNR_TKA': {'fonksiyon_adi': 'TOPLU KONUT ALANI SINIRI',
             'fonksiyon_kodu': '114108',
             'geometri': 'POLYGON',
             'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
             'ust_grup_id': '114000'},
 'SNR_TURIZM_KORUMA': {'fonksiyon_adi': 'TURİZM MERKEZİ/KÜLTÜR VE TURİZM KORUMA VE GELİŞİM ALT '
                                        'BÖLGE SINIRI',
                       'fonksiyon_kodu': '114109',
                       'geometri': 'POLYGON',
                       'ust_grup_adi': 'ÖZEL KANUNLARLA BELİRLENEN ALAN VE SINIRLAR',
                       'ust_grup_id': '114000'},
 'SNR_ULKE': {'fonksiyon_adi': 'ÜLKE SINIRI',
              'fonksiyon_kodu': '121107',
              'geometri': 'POLYGON',
              'ust_grup_adi': 'İDARİ SINIRLAR',
              'ust_grup_id': '121000'},
 'SNR_YAPIYAK': {'fonksiyon_adi': 'YAPI YAKLAŞMA SINIRI',
                 'fonksiyon_kodu': '122110',
                 'geometri': 'POLYGON',
                 'ust_grup_adi': 'PLANLAMA SINIRLARI',
                 'ust_grup_id': '122000'},
 'TESCILLI_ANIT_YAPI': {'fonksiyon_adi': 'TESCİLLİ ANIT YAPI',
                        'fonksiyon_kodu': '113025',
                        'geometri': 'POLYGON',
                        'ust_grup_adi': 'KORUNACAK ALANLAR',
                        'ust_grup_id': '113000'},
 'TESCILLI_BINA': {'fonksiyon_adi': 'TESCİLLİ BİNA',
                   'fonksiyon_kodu': '113026',
                   'geometri': 'POLYGON',
                   'ust_grup_adi': 'KORUNACAK ALANLAR',
                   'ust_grup_id': '113000'},
 'TESCILLI_PARSEL': {'fonksiyon_adi': 'TESCİLLİ PARSEL',
                     'fonksiyon_kodu': '113027',
                     'geometri': 'POLYGON',
                     'ust_grup_adi': 'KORUNACAK ALANLAR',
                     'ust_grup_id': '113000'},
 'TESCILLI_TAB_VARLIGI': {'fonksiyon_adi': 'TESCİLLİ TABİAT VARLIĞI',
                          'fonksiyon_kodu': '113028',
                          'geometri': 'POLYGON',
                          'ust_grup_adi': 'KORUNACAK ALANLAR',
                          'ust_grup_id': '113000'}}

MPYY_ALIASES = {'PL_BELEDIYE': 'PL_BHA',
 'PL_DERE': 'PL_SU_YUZEYI',
 'PL_HAL': 'PL_TOPTAN_TICARET',
 'PL_MERA': 'PL_MERA_ALANI',
 'PL_MEZARLIK_ALANI': 'PL_MEZARLIK',
 'PL_ORMAN': 'PL_ORMAN_ALANI',
 'PL_OYUN_ALANI': 'PL_COCUK_BAHCESI',
 'PL_SAGLIK_OCAGI': 'PL_AILE_SAGL_MER',
 'PL_SOSYOKULTUREL': 'PL_SOSYAL_TESIS',
 'PL_SPOR_TESISLERI': 'PL_ACIK_SPOR_TES',
 'PL_ZEYTINLIK': 'PL_ZEYTINLIK_ALAN'}
